export const featureLabels = {
  advanced_reports: 'Relatorios avancados',
  campaigns: 'Campanhas e promocoes',
  ai_product_descriptions: 'IA para descricao de produtos',
  multi_users: 'Multiplos usuarios',
  whatsapp_integration: 'Integracao WhatsApp',
  analytics: 'Analytics Pro',
  loyalty_program: 'Programa de fidelidade',
  own_delivery: 'Delivery proprio',
  coupon_automation: 'Automacao de cupons',
  priority_support: 'Suporte prioritario',
  featured_home: 'Destaque na home',
  financial_suite: 'Financeiro completo',
  crm: 'CRM de clientes',
  api_access: 'API access',
  white_label: 'White label',
  team_management: 'Gestao de equipe',
  kitchen_display: 'Tela de cozinha',
  internal_courier: 'Entregador interno',
} as const;
