#!/usr/bin/env node
/**
 * memory-derive.ts — Cognitive Memory v2
 *
 * Lê .opencode/memory/state/phases.jsonl (canônico append-only) e gera:
 *   - docs/obsidian/project-operating-system/STATE_ACTIVA.md (HOT, ≤2 KB, só fases ativas)
 *   - docs/obsidian/project-operating-system/CURRENT_STATE.md  (COLD, view histórica completa)
 *
 * Uso:
 *   tsx scripts/memory/derive.ts                # gera
 *   tsx scripts/memory/derive.ts --check       # valida drift (exit 1 se divergente)
 *   tsx scripts/memory/derive.ts --stats        # imprime métricas de token
 *
 * Invariantes:
 *   - phases.jsonl é append-only; nunca editado retroativamente
 *   - arquivos gerados começam com `<!-- generated by memory-derive -->` (idempotente)
 *   - schema é validado por linha; linha inválida = exit 1 com mensagem
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { emit as emitTelemetry } from "./telemetry.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");
const SCHEMA_PATH = resolve(ROOT, ".opencode/memory/schema/phases.schema.json");
const JSONL_PATH = resolve(ROOT, ".opencode/memory/state/phases.jsonl");
const ACTIVA_PATH = resolve(ROOT, "docs/obsidian/project-operating-system/STATE_ACTIVA.md");
const HISTORICO_PATH = resolve(ROOT, "docs/obsidian/project-operating-system/CURRENT_STATE.md");
const GENERATED_MARKER = "<!-- generated by memory-derive -->";

type Status = "open" | "in_progress" | "blocked" | "done" | "archived";
type Category = "phase" | "milestone" | "sprint" | "audit" | "decision" | "blocker" | "refactor";

interface Phase {
  id: string;
  date: string;
  closed_at?: string;
  title: string;
  status: Status;
  category: Category;
  summary?: string;
  owner?: string;
  tags?: string[];
  refs?: string[];
  blockers?: string[];
}

const ACTIVE_STATUSES: ReadonlySet<Status> = new Set(["open", "in_progress", "blocked"]);
const VALID_STATUSES: ReadonlySet<Status> = new Set(["open", "in_progress", "blocked", "done", "archived"]);
const VALID_CATEGORIES: ReadonlySet<Category> = new Set([
  "phase", "milestone", "sprint", "audit", "decision", "blocker", "refactor",
]);
const ID_PATTERN = /^[a-z0-9]+-[a-z0-9-]+$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

class ValidationError extends Error {
  constructor(message: string, public line: number) {
    super(`phases.jsonl:${line} — ${message}`);
  }
}

function parseAndValidate(raw: string): Phase[] {
  const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);
  const phases: Phase[] = [];
  const seenIds = new Set<string>();

  lines.forEach((line, idx) => {
    const lineNo = idx + 1;
    let entry: unknown;
    try {
      entry = JSON.parse(line);
    } catch (e) {
      throw new ValidationError(`JSON inválido: ${(e as Error).message}`, lineNo);
    }
    if (typeof entry !== "object" || entry === null) {
      throw new ValidationError("entrada não é objeto", lineNo);
    }
    const p = entry as Record<string, unknown>;

    for (const field of ["id", "date", "title", "status", "category"] as const) {
      if (typeof p[field] !== "string" || (p[field] as string).length === 0) {
        throw new ValidationError(`campo obrigatório ausente ou inválido: ${field}`, lineNo);
      }
    }
    if (!ID_PATTERN.test(p.id as string)) {
      throw new ValidationError(`id fora do padrão ^[a-z0-9]+-[a-z0-9-]+$: ${p.id}`, lineNo);
    }
    if (seenIds.has(p.id as string)) {
      throw new ValidationError(`id duplicado: ${p.id}`, lineNo);
    }
    seenIds.add(p.id as string);
    if (!DATE_PATTERN.test(p.date as string)) {
      throw new ValidationError(`date fora do formato YYYY-MM-DD: ${p.date}`, lineNo);
    }
    if (!VALID_STATUSES.has(p.status as Status)) {
      throw new ValidationError(`status inválido: ${p.status}`, lineNo);
    }
    if (!VALID_CATEGORIES.has(p.category as Category)) {
      throw new ValidationError(`category inválida: ${p.category}`, lineNo);
    }
    if (p.closed_at !== undefined && !DATE_PATTERN.test(p.closed_at as string)) {
      throw new ValidationError(`closed_at fora do formato YYYY-MM-DD: ${p.closed_at}`, lineNo);
    }
    if (p.summary !== undefined && (typeof p.summary !== "string" || (p.summary as string).length > 1000)) {
      throw new ValidationError(`summary ausente, não-string ou >1000 chars`, lineNo);
    }
    if (p.tags !== undefined && !Array.isArray(p.tags)) {
      throw new ValidationError(`tags deve ser array de strings`, lineNo);
    }
    if (p.refs !== undefined && !Array.isArray(p.refs)) {
      throw new ValidationError(`refs deve ser array de strings`, lineNo);
    }

    phases.push(p as unknown as Phase);
  });

  return phases;
}

function generateActiva(phases: Phase[], now: string): { content: string; stable: string } {
  const active = phases.filter((p) => ACTIVE_STATUSES.has(p.status));
  const sorted = [...active].sort((a, b) => a.date.localeCompare(b.date));
  const counts = {
    open: active.filter((p) => p.status === "open").length,
    in_progress: active.filter((p) => p.status === "in_progress").length,
    blocked: active.filter((p) => p.status === "blocked").length,
  };

  const lines: string[] = [];
  lines.push("---");
  lines.push("type: state");
  lines.push("status: active");
  lines.push("generated: true");
  lines.push(`generated_at: ${now}`);
  lines.push("source: .opencode/memory/state/phases.jsonl");
  lines.push(`counts: { open: ${counts.open}, in_progress: ${counts.in_progress}, blocked: ${counts.blocked} }`);
  lines.push("---");
  lines.push("");
  lines.push(GENERATED_MARKER);
  lines.push("# STATE ACTIVA");
  lines.push("");
  lines.push("> Gerado de `.opencode/memory/state/phases.jsonl`. Não editar à mão.");
  lines.push("> Para atualizar: editar o jsonl e rodar `npm run memory:derive`.");
  lines.push("");
  lines.push(`## Active Phases (${active.length})`);
  lines.push("");

  if (sorted.length === 0) {
    lines.push("_Nenhuma fase ativa no momento._");
    lines.push("");
  } else {
    for (const p of sorted) {
      const statusEmoji = p.status === "blocked" ? "[BLOCKED]" : p.status === "in_progress" ? "[WIP]" : "[OPEN]";
      lines.push(`### ${p.id} ${statusEmoji}`);
      lines.push(`**Title**: ${p.title}`);
      lines.push(`**Status**: \`${p.status}\` · **Category**: \`${p.category}\` · **Since**: ${p.date}`);
      if (p.owner) lines.push(`**Owner**: ${p.owner}`);
      if (p.summary) lines.push(`\n${p.summary}`);
      if (p.refs && p.refs.length > 0) {
        lines.push(`\n**Refs**: ${p.refs.map((r) => `\`${r}\``).join(", ")}`);
      }
      if (p.blockers && p.blockers.length > 0) {
        lines.push(`\n**Blockers**: ${p.blockers.join(", ")}`);
      }
      lines.push("");
    }
  }

  lines.push("## Quick Status");
  lines.push("");
  lines.push("| Frontend | Backend | Lint | Build | Auth Suite |");
  lines.push("|:--------:|:-------:|:----:|:-----:|:----------:|");
  lines.push("| ✅ 52 páginas | ⚠️ 57 TS errors (server/) | ✅ 0 erros (src/) | ✅ | ✅ 20/20 |");
  lines.push("");
  lines.push("## Cognitive Budget (Memory v2)");
  lines.push("");
  lines.push(`- STATE_ACTIVA: ${counts.open + counts.in_progress + counts.blocked} fases ativas (HOT, ≤2 KB)`);
  lines.push(`- phases.jsonl: ${phases.length} entries (canônico, append-only)`);
  lines.push(`- CURRENT_STATE: ${phases.length} entries (COLD, view histórica)`);
  lines.push("");

  const content = lines.join("\n");
  // "stable" = conteúdo sem o timestamp gerado, para comparação de drift sem ruído
  const stable = content.replace(/^generated_at: .+$/m, "generated_at: <ts>");
  return { content, stable };
}

function generateHistorico(phases: Phase[], now: string): { content: string; stable: string } {
  const sorted = [...phases].sort((a, b) => b.date.localeCompare(a.date));
  const lines: string[] = [];
  lines.push("---");
  lines.push("type: state");
  lines.push("status: derived");
  lines.push("generated: true");
  lines.push(`generated_at: ${now}`);
  lines.push("source: .opencode/memory/state/phases.jsonl");
  lines.push(`total_entries: ${phases.length}`);
  lines.push("---");
  lines.push("");
  lines.push(GENERATED_MARKER);
  lines.push("# CURRENT STATE (view histórica completa)");
  lines.push("");
  lines.push(`> Gerado de \`.opencode/memory/state/phases.jsonl\`. View histórica completa — ${phases.length} entries.`);
  lines.push("> Para estado ativo (HOT), consulte `STATE_ACTIVA.md`.");
  lines.push("> Este arquivo é read-only; para mutar, edite `phases.jsonl` e rode `npm run memory:derive`.");
  lines.push("");

  for (const p of sorted) {
    const statusEmoji = ACTIVE_STATUSES.has(p.status)
      ? `[${p.status.toUpperCase()}]`
      : p.status === "done"
        ? "[DONE]"
        : "[ARCH]";
    lines.push(`## ${p.title} ${statusEmoji}`);
    lines.push("");
    lines.push(`- **id**: \`${p.id}\` · **category**: \`${p.category}\` · **date**: ${p.date}${p.closed_at ? ` · **closed**: ${p.closed_at}` : ""}`);
    if (p.owner) lines.push(`- **owner**: ${p.owner}`);
    if (p.tags && p.tags.length > 0) lines.push(`- **tags**: ${p.tags.map((t) => `\`${t}\``).join(", ")}`);
    if (p.summary) lines.push(`\n${p.summary}`);
    if (p.refs && p.refs.length > 0) {
      lines.push(`\n**Refs**: ${p.refs.map((r) => `\`${r}\``).join(", ")}`);
    }
    lines.push("");
  }

  const content = lines.join("\n");
  const stable = content.replace(/^generated_at: .+$/m, "generated_at: <ts>");
  return { content, stable };
}

function main(): void {
  const args = process.argv.slice(2);
  const checkMode = args.includes("--check");
  const statsMode = args.includes("--stats");

  if (!existsSync(SCHEMA_PATH)) {
    console.error(`[memory-derive] ERRO: schema não encontrado: ${SCHEMA_PATH}`);
    process.exit(1);
  }
  if (!existsSync(JSONL_PATH)) {
    console.error(`[memory-derive] ERRO: canônico não encontrado: ${JSONL_PATH}`);
    process.exit(1);
  }

  const raw = readFileSync(JSONL_PATH, "utf-8");
  let phases: Phase[];
  try {
    phases = parseAndValidate(raw);
  } catch (e) {
    if (e instanceof ValidationError) {
      console.error(`[memory-derive] ERRO validação: ${e.message}`);
    } else {
      console.error(`[memory-derive] ERRO inesperado: ${(e as Error).message}`);
    }
    process.exit(1);
  }

  const now = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  const activaOut = generateActiva(phases, now);
  const historicoOut = generateHistorico(phases, now);

  if (checkMode) {
    let drift = false;
    if (existsSync(ACTIVA_PATH)) {
      const onDiskActiva = readFileSync(ACTIVA_PATH, "utf-8").replace(/^generated_at: .+$/m, "generated_at: <ts>");
      if (onDiskActiva !== activaOut.stable) drift = true;
    } else {
      drift = true;
    }
    if (existsSync(HISTORICO_PATH)) {
      const onDiskHistorico = readFileSync(HISTORICO_PATH, "utf-8").replace(/^generated_at: .+$/m, "generated_at: <ts>");
      if (onDiskHistorico !== historicoOut.stable) drift = true;
    } else {
      drift = true;
    }
    if (drift) {
      console.error("[memory-derive] DRIFT detectado: derivados não correspondem ao canônico.");
      console.error("[memory-derive] Rode: npm run memory:derive");
      process.exit(1);
    }
    console.log("[memory-derive] OK — sem drift.");
    return;
  }

  if (statsMode) {
    const activaBytes = Buffer.byteLength(activaOut.content, "utf-8");
    const historicoBytes = Buffer.byteLength(historicoOut.content, "utf-8");
    const estTokensActiva = Math.ceil(activaBytes / 4);
    const estTokensHistorico = Math.ceil(historicoBytes / 4);
    console.log("[memory-derive] STATS:");
    console.log(`  phases.jsonl entries:   ${phases.length}`);
    console.log(`  STATE_ACTIVA:  ${activaBytes} bytes (~${estTokensActiva} tokens)`);
    console.log(`  CURRENT_STATE: ${historicoBytes} bytes (~${estTokensHistorico} tokens)`);
    console.log(`  active phases: ${phases.filter((p) => ACTIVE_STATUSES.has(p.status)).length}`);
    return;
  }

  writeFileSync(ACTIVA_PATH, activaOut.content, "utf-8");
  writeFileSync(HISTORICO_PATH, historicoOut.content, "utf-8");
  const activaBytes = Buffer.byteLength(activaOut.content, "utf-8");
  const historicoBytes = Buffer.byteLength(historicoOut.content, "utf-8");
  const estTokens = Math.ceil(activaBytes / 4);
  console.log(`[memory-derive] OK — gerados:`);
  console.log(`  STATE_ACTIVA:  ${activaBytes} bytes (~${estTokens} tokens)`);
  console.log(`  CURRENT_STATE: ${historicoBytes} bytes`);
  console.log(`  active phases: ${phases.filter((p) => ACTIVE_STATUSES.has(p.status)).length}`);

  // Telemetria
  try {
    const phasesByStatus: Record<string, number> = {};
    for (const p of phases) phasesByStatus[p.status] = (phasesByStatus[p.status] || 0) + 1;
    emitTelemetry("derive_run", {
      phases_total: phases.length,
      phases_by_status: phasesByStatus,
      activa_bytes: activaBytes,
      historico_bytes: historicoBytes,
    });
  } catch {
    // telemetria opcional
  }
}

main();
