import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach, vi } from "vitest";
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync, copyFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");
const CANONICAL = resolve(ROOT, ".opencode/memory/state/phases.jsonl");
const ACTIVA = resolve(ROOT, "docs/obsidian/project-operating-system/STATE_ACTIVA.md");
const HISTORICO = resolve(ROOT, "docs/obsidian/project-operating-system/CURRENT_STATE.md");
const BACKUP_JSONL = resolve(ROOT, ".opencode/memory/state/.phases.backup.jsonl");
const BACKUP_ACTIVA = resolve(ROOT, ".opencode/memory/state/.activa.backup.md");
const BACKUP_HISTORICO = resolve(ROOT, ".opencode/memory/state/.historico.backup.md");

const SAMPLE = [
  { id: "test-a", date: "2026-01-01", closed_at: "2026-01-10", title: "Fase A", status: "done", category: "phase" },
  { id: "test-b", date: "2026-02-01", title: "Fase B", status: "in_progress", category: "phase", summary: "em curso" },
  { id: "test-c", date: "2026-03-01", title: "Fase C", status: "open", category: "sprint", owner: "qa", tags: ["e2e"] },
  { id: "test-d", date: "2026-04-01", title: "Fase D", status: "blocked", category: "refactor", blockers: ["test-b"] },
].map((o) => JSON.stringify(o)).join("\n") + "\n";

describe("memory-derive (isolated)", () => {
  // 5s default é curto para spawnSync de npx tsx; suite tem deriva em beforeEach
  vi.setConfig({ testTimeout: 15000 });

  beforeAll(() => {
    if (existsSync(CANONICAL)) copyFileSync(CANONICAL, BACKUP_JSONL);
    if (existsSync(ACTIVA)) copyFileSync(ACTIVA, BACKUP_ACTIVA);
    if (existsSync(HISTORICO)) copyFileSync(HISTORICO, BACKUP_HISTORICO);
  });
  afterAll(() => {
    if (existsSync(BACKUP_JSONL)) { copyFileSync(BACKUP_JSONL, CANONICAL); rmSync(BACKUP_JSONL); }
    if (existsSync(BACKUP_ACTIVA)) { copyFileSync(BACKUP_ACTIVA, ACTIVA); rmSync(BACKUP_ACTIVA); }
    if (existsSync(BACKUP_HISTORICO)) { copyFileSync(BACKUP_HISTORICO, HISTORICO); rmSync(BACKUP_HISTORICO); }
  });

  beforeEach(() => {
    writeFileSync(CANONICAL, SAMPLE, "utf-8");
    execSync("npx tsx scripts/memory/derive.ts", { cwd: ROOT, stdio: "pipe" });
  });
  afterEach(() => {
    // restore real canonical
    if (existsSync(BACKUP_JSONL)) copyFileSync(BACKUP_JSONL, CANONICAL);
  });

  it("deriva STATE_ACTIVA contendo apenas fases ativas", () => {
    const activa = readFileSync(ACTIVA, "utf-8");
    expect(activa).toContain("test-b");
    expect(activa).toContain("test-c");
    expect(activa).toContain("test-d");
    expect(activa).not.toContain("test-a");
    expect(activa).toContain("[WIP]");
    expect(activa).toContain("[OPEN]");
    expect(activa).toContain("[BLOCKED]");
  });

  it("STATE_ACTIVA começa com marker generated e frontmatter", () => {
    const activa = readFileSync(ACTIVA, "utf-8");
    expect(activa.startsWith("---")).toBe(true);
    expect(activa).toContain("generated: true");
    expect(activa).toContain("<!-- generated by memory-derive -->");
  });

  it("CURRENT_STATE contém todas as fases (histórico)", () => {
    const historico = readFileSync(HISTORICO, "utf-8");
    expect(historico).toContain("test-a");
    expect(historico).toContain("test-b");
    expect(historico).toContain("test-c");
    expect(historico).toContain("test-d");
    expect(historico).toContain("[DONE]");
  });

  it("--check retorna 0 quando derivado bate com canônico", () => {
    expect(() => {
      execSync("npx tsx scripts/memory/derive.ts --check", { cwd: ROOT, stdio: "pipe" });
    }).not.toThrow();
  }, 15000);

  it("--check detecta drift após mutar o derivado", () => {
    writeFileSync(ACTIVA, "drift injected", "utf-8");
    let exitCode = 0;
    try {
      execSync("npx tsx scripts/memory/derive.ts --check", { cwd: ROOT, stdio: "pipe" });
    } catch (e) {
      exitCode = (e as { status: number }).status;
    }
    expect(exitCode).toBe(1);
  }, 15000);

  it("STATE_ACTIVA fica ≤ 4 KB com sample mínimo", () => {
    const activa = readFileSync(ACTIVA, "utf-8");
    const bytes = Buffer.byteLength(activa, "utf-8");
    expect(bytes).toBeLessThan(4 * 1024);
  });

  it("rejeita id duplicado", () => {
    const bad = SAMPLE + JSON.stringify({ id: "test-a", date: "2026-05-01", title: "dup", status: "open", category: "phase" }) + "\n";
    writeFileSync(CANONICAL, bad, "utf-8");
    let exitCode = 0;
    try {
      execSync("npx tsx scripts/memory/derive.ts", { cwd: ROOT, stdio: "pipe" });
    } catch (e) {
      exitCode = (e as { status: number }).status;
    }
    expect(exitCode).toBe(1);
  });

  it("rejeita status inválido", () => {
    const bad = JSON.stringify({ id: "bad-x", date: "2026-01-01", title: "Bad", status: "nope", category: "phase" }) + "\n";
    writeFileSync(CANONICAL, bad, "utf-8");
    let exitCode = 0;
    try {
      execSync("npx tsx scripts/memory/derive.ts", { cwd: ROOT, stdio: "pipe" });
    } catch (e) {
      exitCode = (e as { status: number }).status;
    }
    expect(exitCode).toBe(1);
  });
});
