export const indexDefinitions = {
  core: [
    'idx_restaurants_category ON restaurants (category_id)',
    'idx_restaurants_slug ON restaurants (slug)',
    'idx_menu_items_restaurant ON menu_items (restaurant_id)',
    'idx_menu_items_category ON menu_items (category)',
    'idx_additives_menu_item ON additives (menu_item_id)',
    'idx_categories_slug ON categories (slug)',
  ],
  customer: [
    'idx_addresses_user ON addresses (user_id)',
    'idx_orders_user ON orders (user_id, created_at DESC)',
    'idx_orders_restaurant ON orders (restaurant_id)',
    'idx_orders_status ON orders (status)',
    'idx_orders_address ON orders (address_id)',
    'idx_order_items_order ON order_items (order_id)',
    'idx_order_items_menu_item ON order_items (menu_item_id)',
    'idx_reviews_restaurant ON reviews (restaurant_id)',
    'idx_reviews_user ON reviews (user_id)',
    'idx_users_email ON users (email)',
    'idx_users_role ON users (role)',
  ],
  merchant: [
    'idx_branches_company ON branches (company_id)',
    'idx_merchant_orders_branch ON merchant_orders (branch_id, status)',
    'idx_merchant_orders_created ON merchant_orders (created_at DESC)',
    'idx_merchant_order_items_order ON merchant_order_items (merchant_order_id)',
    'idx_merchant_menu_items_branch ON merchant_menu_items (branch_id)',
    'idx_companies_document ON companies (document)',
  ],
  commerce: [
    'idx_global_coupons_code ON global_coupons (code)',
    'idx_global_coupons_active ON global_coupons (is_active, valid_until)',
    'idx_merchant_coupons_branch ON merchant_coupons (branch_id)',
    'idx_merchant_coupons_code ON merchant_coupons (code)',
    'idx_campaigns_branch ON campaigns (branch_id)',
    'idx_campaigns_status ON campaigns (status)',
  ],
  saas: [
    'idx_subscriptions_company ON subscriptions (company_id)',
    'idx_subscriptions_status ON subscriptions (billing_status)',
    'idx_invoices_company ON invoices (company_id)',
    'idx_invoices_status ON invoices (status)',
    'idx_invoices_due_date ON invoices (due_date)',
    'idx_feature_flags_company ON feature_flags (company_id)',
    'idx_feature_flags_branch ON feature_flags (branch_id)',
    'idx_feature_flags_user ON feature_flags (user_id)',
    'idx_feature_flags_key ON feature_flags (feature_key)',
    'idx_capabilities_key ON capabilities (feature_key)',
    'idx_addons_feature_key ON addons (feature_key)',
  ],
  ops: [
    'idx_notifications_created ON notifications (created_at DESC)',
    'idx_notifications_target ON notifications (target)',
    'idx_coverage_cities_name_state ON coverage_cities (name, state)',
    'idx_coverage_cities_active ON coverage_cities (is_active)',
    'idx_audit_events_created ON audit_events (created_at DESC)',
    'idx_audit_events_actor ON audit_events (actor_id)',
    'idx_support_tickets_user ON support_tickets (user_id)',
    'idx_support_tickets_status ON support_tickets (status)',
    'idx_user_notifications_user ON user_notifications (user_id, created_at DESC)',
    'idx_user_notifications_read ON user_notifications (user_id, read)',
  ],
} as const;
