import {
  AlertTriangle, ArrowRight, ArrowUpRight, Award,
  Bell, Building2,
  Calendar, Check, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock, CreditCard, Crosshair, Crown,
  Database, DollarSign,
  FileCode, FileSpreadsheet, FileText, Flag,
  Gift,
  Headset, Heart, House,
  ImageOff, Info,
  LayoutDashboard, List, Loader, Lock,
  Map, MapPin, Megaphone, Menu, Minus, Monitor, Moon,
  Package, PackagePlus, Pen, Pencil, Percent, Plus, Printer, Puzzle,
  Receipt, RefreshCw,
  Search, SearchX, Shield, ShoppingBag, Star, Store, Sun,
  Tag, Trash2, TrendingUp, Truck,
  User, Users, UtensilsCrossed, Zap,
  X, XCircle,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  AlertTriangle, ArrowRight, ArrowUpRight, Award,
  Bell, Building2,
  Calendar, Check, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock, CreditCard, Crosshair, Crown,
  Database, DollarSign,
  FileCode, FileSpreadsheet, FileText, Flag,
  Gift,
  Headset, Heart, House,
  ImageOff, Info,
  LayoutDashboard, List, Loader, Lock,
  Map, MapPin, Megaphone, Menu, Minus, Monitor, Moon,
  Package, PackagePlus, Pen, Pencil, Percent, Plus, Printer, Puzzle,
  Receipt, RefreshCw,
  Search, SearchX, Shield, ShoppingBag, Star, Store, Sun,
  Tag, Trash2, TrendingUp, Truck,
  User, Users, UtensilsCrossed, Zap,
  X, XCircle,
};
